name: Update Climate NLP Papers

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at 00:00 on the first day of every month
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-papers:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          uv sync
      
      - name: Fetch papers
        run: python scripts/fetch_papers.py data/papers.jsonl
        env:
          EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update climate NLP papers'
          title: 'Update Climate NLP Papers Dataset'
          body: |
            Automated update of climate NLP papers dataset.
            
            This PR was automatically created by the monthly paper update workflow.
          branch: update-papers
          delete-branch: true 